# Generated by Django 5.0.1 on 2024-03-19 11:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vet_clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pet_info', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('date_for_visit', models.DateField()),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('CMP', 'Complete'), ('CNF', 'Confirm'), ('DLY', 'Delay')], default='DRF', max_length=3)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='vet_clinic.service')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['-order_date'], name='pet_care_sc_order_d_30f611_idx')],
            },
        ),
    ]
