# Generated by Django 5.0.1 on 2024-01-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comm_content',
        ),
    ]
