# Generated by Django 5.0.1 on 2024-01-25 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0013_post_users_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('CMP', 'Complete'), ('CNF', 'Confirm'), ('DLY', 'Delay')], default='DRF', max_length=3),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='vet_clinic__order_d_e18345_idx'),
        ),
    ]
