# Generated by Django 5.0.1 on 2024-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0014_alter_order_options_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['-publish_date'], name='vet_clinic__publish_7722ca_idx'),
        ),
    ]
