# Generated by Django 5.0.1 on 2024-03-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0015_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
