# Generated by Django 5.0.1 on 2024-01-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
