# Generated by Django 5.0.1 on 2024-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
